# Generated by Django 5.1.3 on 2025-02-17 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        ('data', '0006_alter_detectionresult_case_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=50, unique=True)),
                ('tenant_id', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=100)),
                ('client_secret', models.CharField(max_length=100)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('validated', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_azure_accounts', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azure_accounts', to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='AzureLogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('log_name', models.CharField(max_length=255)),
                ('log_details', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sources', to='azure.azureaccount')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azure_log_sources', to='case.case')),
                ('tags', models.ManyToManyField(related_name='azure_log_source', to='data.tag')),
            ],
        ),
        migrations.CreateModel(
            name='AzureResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=200)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_name', models.CharField(blank=True, max_length=200, null=True)),
                ('resource_group', models.CharField(max_length=200)),
                ('resource_details', models.JSONField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='azure.azureaccount')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azure_resources', to='case.case')),
                ('tags', models.ManyToManyField(related_name='azure_resource', to='data.tag')),
            ],
        ),
        migrations.CreateModel(
            name='AzureIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=300)),
                ('user_principal_name', models.CharField(blank=True, max_length=300, null=True)),
                ('identity_type', models.CharField(max_length=50)),
                ('mfa_enabled', models.BooleanField(default=False)),
                ('created_datetime', models.DateTimeField(blank=True, null=True)),
                ('last_sign_in', models.DateTimeField(blank=True, null=True)),
                ('account_enabled', models.BooleanField(default=True)),
                ('assigned_roles', models.JSONField(blank=True, null=True)),
                ('identity_details', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='azure.azureaccount')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='azure_identities', to='case.case')),
                ('tags', models.ManyToManyField(related_name='azure_identity', to='data.tag')),
            ],
            options={
                'verbose_name_plural': 'Azure identities',
                'unique_together': {('account', 'object_id')},
            },
        ),
    ]
