# Generated by Django 5.1.3 on 2025-02-13 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('case', '0001_initial'),
        ('data', '0004_alter_normalizedlog_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_results', to='case.case')),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analysis.detection')),
                ('matched_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_matches', to='data.normalizedlog')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='data_detect_created_0a2c78_idx')],
            },
        ),
    ]
