# Generated by Django 5.1.3 on 2025-02-14 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('case', '0001_initial'),
        ('data', '0005_detectionresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionresult',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case.case'),
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.detection'),
        ),
        migrations.AlterField(
            model_name='detectionresult',
            name='matched_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.normalizedlog'),
        ),
    ]
