# Generated by Django 5.1.3 on 2025-02-18 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure', '0001_initial'),
        ('data', '0006_alter_detectionresult_case_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedlog',
            name='azure_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalized_logs', to='azure.azureaccount'),
        ),
    ]
