# Generated by Django 5.1.3 on 2025-02-18 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0002_awscredential_tags_awslogsource_tags_and_more'),
        ('data', '0007_normalizedlog_azure_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedlog',
            name='aws_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalized_logs', to='aws.awsaccount'),
        ),
    ]
