# Generated by Django 5.1.3 on 2025-02-26 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case', '0001_initial'),
        ('data', '0008_alter_normalizedlog_aws_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100, unique=True)),
                ('service_account_info', models.JSONField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('validated', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_gcp_accounts', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcp_accounts', to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='GCPLogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('log_name', models.CharField(max_length=255)),
                ('log_details', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sources', to='gcp.gcpaccount')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcp_log_sources', to='case.case')),
                ('tags', models.ManyToManyField(related_name='gcp_log_source', to='data.tag')),
            ],
        ),
        migrations.CreateModel(
            name='GCPResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=200)),
                ('resource_type', models.CharField(max_length=100)),
                ('resource_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('resource_details', models.JSONField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='gcp.gcpaccount')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcp_resources', to='case.case')),
                ('tags', models.ManyToManyField(related_name='gcp_resource', to='data.tag')),
            ],
        ),
    ]
